### ISSUE TITLE
Compile log4cxx statically

### ISSUE THREAD

**Issue by natale-p** [apache/logging-log4cxx#194]
In https://github.com/apache/logging-log4cxx/blob/master/src/main/include/log4cxx/private/log4cxx_private.h.in we see:

```
#if !defined(LOG4CXX) && !defined(LOG4CXX_TEST)
#error "log4cxx/private/log4cxx_private.h should only be used within log4cxx implementation or tests"
#endif
```

But when compiling statically (`-DBUILD_SHARED_LIBS=OFF`) the definition added is `LOG4CXX_STATIC`, not `LOG4CXX`. Is that intended?

Thanks

**Comment by swebb2066** [comment]
Private header files are not _installed_ since log4cxx version 1.0, so the `#if !defined(LOG4CXX) && !defined(LOG4CXX_TEST)` test in log4cxx_private.h is only relevent to log4cxx developers.

Could you describe the issue you encountered?

**Comment by rm5248** [comment]
I noticed this a few weeks ago, but I think the problem may be coming from about this part of the src/main/cpp/CMakeLists.txt: https://github.com/apache/logging-log4cxx/blob/afeaab6d0f0107c77dfadcbe3708f170c48d5ed9/src/main/cpp/CMakeLists.txt#L23

I think that most files that need to use the private header are simply doing `#define LOG4CXX 1` before they include the private header.  I can't remember if this caused an issue or not, I can't get it to happen on Linux at least.  It seems that `LOG4CXX` should always be defined(since we are compiling the library), but `LOG4CXX_STATIC` should only be defined if building a static library.

**Comment by natale-p** [comment]
I forgot to indicate that the problem is with log4cxx 0.13. I tried reproducing with the latest version, but it compiles correctly: no issue. So I suppose this issue can be closed, but for reference, it can be solved with the following:

```
diff --git i/src/main/include/log4cxx/private/log4cxx_private.h.in w/src/main/include/log4cxx/private/log4cxx_private.h.in
index 61e8e7ac..0e8dfb14 100644
--- i/src/main/include/log4cxx/private/log4cxx_private.h.in
+++ w/src/main/include/log4cxx/private/log4cxx_private.h.in
@@ -26,7 +26,7 @@

 #include <log4cxx/log4cxx.h>

-#if !defined(LOG4CXX) && !defined(LOG4CXX_TEST)
+#if !defined(LOG4CXX) && !defined(LOG4CXX_TEST) && !defined(LOG4CXX_STATIC)
 #error "log4cxx/private/log4cxx_private.h should only be used within log4cxx implementation or tests"
 #endif

```

(or with upgrading to 1.0.0)
